서브쿼리
- from 과 where 절에서 주로 쓰는게 좋음;




SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'JONES');
             
             
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.DEPTNO = 20
   AND E.SAL > (SELECT AVG(SAL)
                  FROM EMP);
                  
                  
SELECT *
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL) 
                FROM EMP 
                GROUP BY DEPTNO);


SELECT * FROM EMP
WHERE SAL IN (SELECT SAL FROM EMP
                WHERE DEPTNO = 30)
ORDER BY SAL;


SELECT * FROM EMP
WHERE SAL = SOME (SELECT MAX(SAL) FROM EMP
                GROUP BY DEPTNO)
ORDER BY SAL;


SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT
                WHERE DEPTNO = 10);
        
                
SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT
                WHERE DEPTNO = 60); --DEPTNO = 60 NOT EXIST


SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                        FROM EMP
                        GROUP BY DEPTNO);
                        
                        
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
       (SELECT * FROM DEPT) D
 WHERE E10.DEPTNO = D.DEPTNO;
 

SELECT EMPNO, ENAME, JOB, SAL,
       (SELECT GRADE 
          FROM SALGRADE
         WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DEPTNO,
      (SELECT DNAME
         FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;



--Q1 전체 사원 중 ALLEN과 같은 직책의 사원들의 사원 정보, 부서 정보를 다음과 같이 출력해라
SELECT JOB, EMPNO, ENAME, SAL, D.DEPTNO, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');


--Q2 전체 사원의 평균 급여보다 높은 급여를 받는 사원들의 사원 정보, 부서 정보, 급여 등급 정보를 출력해라
SELECT EMPNO, ENAME, DNAME, HIREDATE, LOC, SAL--, GRADE
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO;


--Q3 10번 부서에 근무하는 사원 중 30번 부서에는 존재하지 않는 직책을 가진 사원들의 사원 정보, 부서 정보를 출력해라
SELECT EMPNO, ENAME, JOB, D.DEPTNO, DNAME, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND D.DEPTNO = 10
AND JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = 30);


--Q4 직책이 SALESMAN인 사람들의 최고 급여보다 높은 급여를 받는 사원들의 사원 정보, 급여 등급 정보를 출력해라
SELECT EMPNO, ENAME, SAL--, GRADE
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN');
