-- 실습 12-1
DROP TABLE EMP_DDL;

CREATE TABLE EMP_DDL(
   EMPNO      NUMBER(4),
   ENAME      VARCHAR2(10),
   JOB        VARCHAR2(9),
    MG        NUMBER(4),
   HIREDATE   DATE,
   SAL        NUMBER(7,2),
   COMM       NUMBER(7,2),
   DEPTNO     NUMBER(2)
);

DESC EMP_DDL;

SELECT *
FROM   EMP_DDL;

-- 실습 12-2
DROP TABLE DEPT_DDL;

CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;

DESC DEPT_DDL;

SELECT *
FROM   DEPT_DDL;

-- 실습 12-3
SELECT * FROM DEPT_DDL;

-- 실습 12-4
DROP TABLE EMP_DDL_30;

CREATE TABLE EMP_DDL_30
    AS SELECT *
         FROM EMP
        WHERE DEPTNO = 30;

SELECT * FROM EMP_DDL_30;

-- 실습 12-5
DROP TABLE EMPDEPT_DDL;
CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E. MG, E.HIREDATE,
              E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
         FROM EMP E, DEPT D
        --WHERE 1 <> 1
;

SELECT * FROM EMPDEPT_DDL;

-- 실습 12-6
DROP TABLE  EMP_ALTER;
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

-- 실습 12-7
ALTER TABLE EMP_ALTER
  ADD HP VARCHAR2(20);  --칼럼 데이터 타입 바꾸기

SELECT * FROM EMP_ALTER;

-- 실습 12-8
ALTER TABLE EMP_ALTER
RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER;

-- 실습 12-9
ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

-- 실습 12-10
ALTER TABLE EMP_ALTER
 DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

-- 실습 12-11
RENAME EMP_ALTER TO EMP_RENAME;

-- 실습 12-12
DESC EMP_ALTER;

-- 실습 12-13
SELECT *
  FROM EMP_RENAME;

-- 실습 12-14
TRUNCATE TABLE EMP_RENAME;  --테이블 삭제 안하고 데이터만 지움
DELETE TABLE EMP_RENAME;    --테이블 삭제 안하고 데이터만 지움. 시간이 많이 걸림. DML

SELECT *
  FROM EMP_RENAME;

-- 실습 12-15
DROP TABLE EMP_RENAME;  --테이블 삭제

SELECT *
  FROM EMP_RENAME;
  
-- 실습 12-16
DESC EMP_RENAME;





--Q1 다음 열 구조를 가지는 EMP_HW 테이블을 만들어라
CREATE TABLE EMP_HW(
   EMPNO      NUMBER(4),
   ENAME      VARCHAR2(10),
   JOB        VARCHAR2(9),
    MGR        NUMBER(4),
   HIREDATE   DATE,
   SAL        NUMBER(7,2),
   COMM       NUMBER(7,2),
   DEPTNO     NUMBER(2)
);

DESC EMP_HW;
SELECT * FROM EMP_HW;


--Q2 BIGO 열을 추가해라(자료형은 가변형 문자열, 길이는 20)
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);


--Q3 BIGO 열 크기를 30으로 변경해라
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);


--Q4 BIGO 열 이름을 REMARK로 변경해라 
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;


--Q5 EMP_HW 테이블에 EMP 테이블의 데이터를 모두 저장해라(REMARK 열은 NULL로)
INSERT INTO EMP_HW
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL 
FROM EMP;


--Q6 EMP_HW 테이블을 삭제해라 
DROP TABLE EMP_HW;
