SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD')
FROM DUAL
WHERE SYSDATE = '23/05/03';

DESC DUAL;


SELECT *    --SUBSTR (ENAME, 1, 2)
FROM EMP;


SELECT JOB, LENGTH(JOB), SUBSTR (JOB, 2,3)
FROM EMP;


SELECT RTRIM('_ _ORACLE_ _')
FROM DUAL;


SELECT ROUND(1)
FROM DUAL;


SELECT TO_CHAR(HIREDATE, 'YYYY-MM-DD') AS 입사일
FROM EMP;


--날짜 포맷 변경
SELECT SYSDATE,
TO_CHAR(SYSDATE, 'MM') AS 입사일,
TO_CHAR(SYSDATE, 'MON') AS 입사일,
TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS 입사일
FROM DUAL;


--숫자 천단위, 소수자리 표시
SELECT SAL,
TO_CHAR(SAL, '$999,999') AS SAL_$,
TO_CHAR(SAL, 'L999,999') AS SAL_L,
TO_CHAR(SAL, '999,999.00') AS SAL_1,
TO_CHAR(SAL, '000,999,999.00') AS SAL_2,
TO_CHAR(SAL, '000999999.99') AS SAL_3,
TO_CHAR(SAL, '999,999,00') AS SAL_4

FROM EMP;



SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1981/06/01', 'YY/MM/DD'); --입사일이 1981/06/01 데이터


--널값 처리
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM,
        NVL(COMM,0),    --널 값에 0 대입
        SAL+NVL(COMM,0)
FROM EMP;


SELECT EMPNO, ENAME, SAL, COMM,
        NVL2(COMM, 'O', 'X'),    --(널이 아닐 경우, 널일 경우)
        NVL2(COMM, SAL*12, SAL*12+COMM)
FROM EMP;



SELECT EMPNO, ENAME, JOB, SAL, 
    CASE JOB
        WHEN 'MGR' THEN SAL*1.1
        WHEN 'SALESMAN' THEN SAL*1.5
        WHEN 'ANALYST' THEN SAL
        ELSE SAL*1.03  --연봉 인상
    END AS UPSAL
     
FROM EMP;


--Q1 
SELECT EMPNO,
        CONCAT(SUBSTR(EMPNO, 1,2), '**') AS MASKING_EMPNO,
        ENAME,
        CONCAT(SUBSTR(ENAME, 1,1), '****') AS MASKING_ENAME
        
FROM EMP
WHERE LENGTH(ENAME) = 5;


--Q2
SELECT EMPNO,
        ENAME,
        SAL,
        TRUNC((SAL/21.5), 2) AS DAY_PAY,
        ROUND(SAL/21.5/8, 1) AS TIME_PAY
        
FROM EMP;


--Q3
SELECT EMPNO, ENAME, TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE, 
        TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월'), 'YYYY-MM-DD') AS R_JOB, NVL2(COMM, '0', 'N/A') AS COMM
FROM EMP
;