조인
- 내추럴 조인
- Equal (등가)
     
- not-equal (비등가)
- Self join
- Outer join(left/right/full)
;


--NATURAL JOIN
    SELECT * FROM emp --중복, 중복제외 EMP, 중복제외 DEPT
    NATURAL JOIN dept;
    
    SELECT * FROM DEPT  --중복, 중복제외 DEPT, 중복제외 EMP
    NATURAL JOIN EMP;
    
--EQUAL JOIN
    SELECT * FROM Emp, Dept
    WHERE Emp.Deptno = Dept.Deptno;
     
    SELECT distinct Dept.deptno FROM Dept, Emp
    WHERE Emp.Deptno = Dept.Deptno;
     
     
    SELECT Emp.*, Dept.* FROM Dept, Emp --LEFT JOIN
    WHERE Emp.Deptno  = Dept.Deptno(+)
    ORDER BY Emp.deptno;
     
    SELECT Emp.*, Dept.* FROM Dept, Emp --RIGHT JOIN
    WHERE Emp.Deptno (+) = Dept.Deptno
    ORDER BY Emp.deptno;
     
    SELECT A.DEPTNO, A.DEPTNO EMP_DEPTNO, B.DEPTNO DEPT_DEPTNO
    FROM EMP A, DEPT B
    WHERE A.DEPTNO = B.DEPTNO
    ORDER BY A.DEPTNO;
     
     
--INER JOIN
    SELECT A.DEPTNO, A.DEPTNO EMP_DNO, B.DEPTNO DEPT_DNO, A.*, B.*
    FROM EMP A INNER JOIN DEPT B
    ON A.DEPTNO = B.DEPTNO;
    

--RIGHT OUTER JOIN
    SELECT A.DEPTNO, A.DEPTNO EMP_DNO, B.DEPTNO DEPT_DNO, A.*, B.*
    FROM EMP A RIGHT OUTER JOIN DEPT B
    ON A.DEPTNO = B.DEPTNO
    ORDER BY A.DEPTNO;


--LEFT OUTER JOIN
    SELECT A.DEPTNO, A.DEPTNO EMP_DNO, B.DEPTNO DEPT_DNO, A.*, B.*
    FROM EMP A LEFT OUTER JOIN DEPT B
    ON A.DEPTNO = B.DEPTNO
    ORDER BY A.DEPTNO;
    

--FULL OUTER JOIN
    SELECT A.DEPTNO, A.DEPTNO EMP_DNO, B.DEPTNO DEPT_DNO, A.*, B.*
    FROM EMP A FULL OUTER JOIN DEPT B
    ON A.DEPTNO = B.DEPTNO
    ORDER BY A.DEPTNO;
    
/*    
INSERT INTO EMP
SELECT * FROM EMP WHERE EMPNO = 7369; */
    
    

SELECT * FROM EMP;  --14

SELECT * FROM DEPT; --4




--Q1
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND SAL > 2000
ORDER BY D.DEPTNO, D.DNAME;


--Q2
SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;
--ORDER BY D.DEPTNO, D.DNAME;


--Q3
SELECT D.DEPTNO, DNAME, E.EMPNO, ENAME, JOB, SAL
FROM EMP E RIGHT OUTER JOIN DEPT D  --DEPT ALL
ON E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;


SELECT * FROM SALGRADE;

--Q4
SELECT D.DEPTNO, DNAME, EMPNO, ENAME, MGR, SAL, E.DEPTNO, S.LOSAL, S.HISAL, GRADE
FROM SALGRADE S, EMP E FULL OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY D.DEPTNO, E.EMPNO;
