서브쿼리
- from 과 where 절에서 주로 쓰는게 좋음;




SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME = 'JONES');
             
             
SELECT E.EMPNO, E.ENAME, E.JOB, E.SAL, D.DEPTNO, D.DNAME, D.LOC
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND E.DEPTNO = 20
   AND E.SAL > (SELECT AVG(SAL)
                  FROM EMP);
                  
                  
SELECT *
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL) 
                FROM EMP 
                GROUP BY DEPTNO);


SELECT * FROM EMP
WHERE SAL IN (SELECT SAL FROM EMP
                WHERE DEPTNO = 30)
ORDER BY SAL;


SELECT * FROM EMP
WHERE SAL = SOME (SELECT MAX(SAL) FROM EMP
                GROUP BY DEPTNO)
ORDER BY SAL;


SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT
                WHERE DEPTNO = 10);
        
                
SELECT * FROM EMP
WHERE EXISTS (SELECT DNAME FROM DEPT
                WHERE DEPTNO = 60); --DEPTNO = 60 NOT EXIST


SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL)
                        FROM EMP
                        GROUP BY DEPTNO);
                        
                        
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
  FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10,
       (SELECT * FROM DEPT) D
 WHERE E10.DEPTNO = D.DEPTNO;
 

SELECT EMPNO, ENAME, JOB, SAL,
       (SELECT GRADE 
          FROM SALGRADE
         WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE,
       DEPTNO,
      (SELECT DNAME
         FROM DEPT
        WHERE E.DEPTNO = DEPT.DEPTNO) AS DNAME
FROM EMP E;



--Q1
SELECT JOB, EMPNO, ENAME, SAL, D.DEPTNO, DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND JOB = (SELECT JOB FROM EMP WHERE ENAME = 'ALLEN');


--Q2
SELECT EMPNO, ENAME, DNAME, HIREDATE, LOC, SAL--, GRADE
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL > (SELECT AVG(SAL) FROM EMP)
ORDER BY SAL DESC, EMPNO;


--Q3
SELECT EMPNO, ENAME, JOB, D.DEPTNO, DNAME, LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND D.DEPTNO = 10
AND JOB NOT IN (SELECT JOB FROM EMP WHERE DEPTNO = 30);


--Q4
SELECT EMPNO, ENAME, SAL--, GRADE
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN');